# Generated by Django 4.0.4 on 2022-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Details',
                'verbose_name_plural': 'Details',
            },
        ),
    ]
